services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - mariadb
      - mongodb
      - redis
    networks:
      - net
    volumes:
      - notebooks_volume:/notebooks
    environment:
      - IPYTHONDIR=/root/.ipython
      - PYTHONPATH=/root/.ipython/extensions
  redis:
    image: "redis:8.0.3-alpine"
    networks:
      - net
    ports:
      - "6379:6379"
  mariadb:
    image: "mariadb:11.8.2"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
    networks:
      - net
    ports:
      - "3306:3306"
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - net
    ports:
      - "27017:27017"

networks:
  net:
    driver: bridge

volumes:
  notebooks_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./notebooks